# Google Cloud Build configuration for automatic deployment
steps:
    # Build the Docker image
    - name: "gcr.io/cloud-builders/docker"
      args:
          [
              "build",
              "-t",
              "gcr.io/$PROJECT_ID/suhtet-portfolio:$COMMIT_SHA",
              "-t",
              "gcr.io/$PROJECT_ID/suhtet-portfolio:latest",
              ".",
          ]

    # Push the Docker image to Container Registry
    - name: "gcr.io/cloud-builders/docker"
      args: ["push", "gcr.io/$PROJECT_ID/suhtet-portfolio:$COMMIT_SHA"]

    - name: "gcr.io/cloud-builders/docker"
      args: ["push", "gcr.io/$PROJECT_ID/suhtet-portfolio:latest"]

    # Deploy to Cloud Run
    - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
      entrypoint: gcloud
      args:
          [
              "run",
              "deploy",
              "suhtet-portfolio",
              "--image",
              "gcr.io/$PROJECT_ID/suhtet-portfolio:$COMMIT_SHA",
              "--region",
              "us-central1",
              "--platform",
              "managed",
              "--allow-unauthenticated",
              "--port",
              "3000",
              "--memory",
              "1Gi",
              "--cpu",
              "1",
              "--max-instances",
              "10",
              "--min-instances",
              "0",
              "--concurrency",
              "80",
              "--timeout",
              "300",
          ]

# Store images in Container Registry
images:
    - "gcr.io/$PROJECT_ID/suhtet-portfolio:$COMMIT_SHA"
    - "gcr.io/$PROJECT_ID/suhtet-portfolio:latest"

# Build configuration
options:
    machineType: "E2_HIGHCPU_8"
    diskSizeGb: "100"
